-- ============================================
-- PROJECT: Blinkit Sales Data Analysis
-- TOOL: MySQL
-- DESCRIPTION: Analyzed sales data to identify top-performing products, outlet types, and business trends.
-- ============================================

-- ============================================
-- 1. TOTAL SALES
-- Objective: Calculate overall revenue generated from all sales
-- ============================================
SELECT SUM(sales) FROM blinkit_data;

-- ============================================
-- 2. SALES BY ITEM TYPE
-- Objective: Analyze which product categories generate the most revenue
-- ============================================
SELECT item_type, SUM(sales)
FROM blinkit_data
GROUP BY item_type;

-- ============================================
-- 3. TOP 5 ITEM TYPES BY SALES
-- Objective: Identify best-performing product categories
-- ============================================
SELECT item_type, SUM(sales)
FROM blinkit_data
GROUP BY item_type
ORDER BY SUM(sales) DESC
LIMIT 5;

-- ============================================
-- 4. SALES BY OUTLET LOCATION TYPE
-- Objective: Compare sales performance across Tier 1, Tier 2, and Tier 3 cities
-- ============================================
SELECT outlet_location_type, SUM(sales)
FROM blinkit_data
GROUP BY outlet_location_type;

-- ============================================
-- 4. SALES BY OUTLET LOCATION TYPE
-- Objective: Compare sales performance across Tier 1, Tier 2, and Tier 3 cities
-- ============================================
SELECT outlet_location_type, SUM(sales) AS total_sales
FROM blinkit_data
GROUP BY outlet_location_type
ORDER BY total_sales DESC
LIMIT 1;

-- ============================================
-- 6. SALES BY OUTLET TYPE
-- Objective: Evaluate performance of different outlet formats (Supermarket, Grocery Store, etc.)
-- ============================================
SELECT outlet_type, SUM(sales) AS total_sales
FROM blinkit_data
GROUP BY outlet_type;

-- ============================================
-- 7. TOP 3 OUTLET TYPES
-- Objective: Identify top-performing outlet types based on revenue
-- ============================================
SELECT outlet_type, SUM(sales) AS total_sales
FROM blinkit_data
GROUP BY outlet_type
ORDER BY total_sales DESC
LIMIT 3;

-- ============================================
-- 8. AVERAGE SALES BY ITEM TYPE
-- Objective: Analyze average performance of each product category
-- ============================================
SELECT item_type, AVG(sales) AS average_sales
FROM blinkit_data
GROUP BY item_type;

-- ============================================
-- 9. ITEM TYPE WITH HIGHEST AVERAGE SALES
-- Objective: Identify category with most consistent high performance
-- ============================================
SELECT item_type, AVG(sales) AS average_sales
FROM blinkit_data
GROUP BY item_type
ORDER BY average_sales DESC
LIMIT 1;

-- ============================================
-- 10. SALES BY OUTLET SIZE
-- Objective: Compare revenue generated by small, medium, and large outlets
-- ============================================
SELECT outlet_size, SUM(sales) AS total_sales
FROM blinkit_data
GROUP BY outlet_size;

-- ============================================
-- 11. LOWEST PERFORMING OUTLET SIZE
-- Objective: Identify outlet size contributing least to total revenue
-- ============================================
SELECT outlet_size, SUM(sales) AS total_sales
FROM blinkit_data
GROUP BY outlet_size
ORDER BY total_sales ASC
LIMIT 1;

-- ============================================
-- 12. TOP 5 PRODUCTS BY SALES
-- Objective: Identify highest-selling products based on total revenue
-- ============================================
SELECT item_identifier, SUM(sales) AS total_sales
FROM blinkit_data
GROUP BY item_identifier
ORDER BY total_sales DESC
LIMIT 5;